# Generated by Django 4.2.14 on 2024-07-22 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productcategory_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="category_name",
        ),
    ]
